[package]
name = "fanwaave-api-server"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "JSON API server for Fanwaave"
repository = "https://github.com/fanwaave/fanwaave-api-server.rs"

[features]
default = ["tcp-transport", "nats-transport"]
tcp-transport = []
nats-transport = []

[dependencies]
async-nats = "0.42"
axum = "0.8"
fanwaave-lib-core = { git = "https://github.com/fanwaave/fanwaave-lib-core.git", rev = "6f46477b54bcbca32d6808421b5af27cfffb3703" }
flags2env = { git = "https://github.com/flags-2-env/flags-2-env.git", rev = "b708a041531a830bd49f030250836896096e7abd" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sqlx = { version = "0.8", default-features = false, features = ["json", "postgres", "runtime-tokio-rustls", "uuid"] }
subtle = "2"
tempfile = "3"
thiserror = "2"
tokio = { version = "1", features = ["macros", "net", "rt-multi-thread", "signal"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }
uuid = { version = "1", features = ["serde"] }

[lints.rust]
unsafe_code = "forbid"
